-- Data Engineering --

-- Drop Tables if Existing
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS dept_employee;
DROP TABLE IF EXISTS dept_manager;
DROP TABLE IF EXISTS salary;
DROP TABLE IF EXISTS title;

-- Tables created all required columns and alll columns set to with correct Data types, Primary Keys & Foreign keys
-- Imported CSV files (Resources folder) into the responding SQL table generated by this code
-- Run (Query * FROM ) Each Table Confirming Data is correctly imported

	CREATE TABLE department (
	  department_id VARCHAR(10) PRIMARY KEY,
	  department_name VARCHAR(50)
	);
	
	CREATE TABLE employee (
	  employee_id INTEGER NOT NULL PRIMARY KEY,
	  title_id VARCHAR(10),
	  birth_date DATE NOT NULL,
	  first_name VARCHAR(50),
	  last_name VARCHAR(50),
	  sex CHAR NOT NULL,
	  hire_date DATE NOT NULL
	);
	
	CREATE TABLE department_employee (
	  employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
	  department_id VARCHAR(10) REFERENCES department(department_id)
	);
	
	CREATE TABLE department_manager(
	  department_id VARCHAR(10) REFERENCES department(department_id),
	  employee_id INTEGER NOT NULL REFERENCES employee(employee_id)
	);
		
	CREATE TABLE salary (
	  employee_id INTEGER NOT NULL REFERENCES employee(employee_id),
	  salary INTEGER NOT NULL
	);

	CREATE TABLE title (
	  title_id VARCHAR(10) PRIMARY KEY,
	  title VARCHAR NOT NULL
	);
		
-- Query * FROM Each Table Confirming Data
SELECT * FROM department;
SELECT * FROM employee;
SELECT * FROM department_employee;
SELECT * FROM department_manager;
SELECT * FROM salary;
SELECT * FROM title;